app/src/main/java/com/simon/harmonichackernews/UserDialogFragment.java

This pull request is to fix an issue with users that do not have a "submissions" key.
If you look at the response for my username, https://hacker-news.firebaseio.com/v0/user/tukajo.json
It returns the following JSON
```
{"created":1650837729,"id":"tukajo","karma":1}
```
This causes an exception to be thrown when the `getJsonArray` is called, which causes the modal to never be able to render the user profile (no matter how many retries).
Addresses #10

fix exception when loading user without submissions

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/WelcomeActivity.java
app/src/main/java/com/simon/harmonichackernews/utils/ThemeUtils.java
app/src/main/res/layout/activity_welcome.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/themes.xml

Thanks for the great app!  I've wanted a dark mode for HN for a long time :)
This new theme automatically follows the system dark/light mode.  Given the existing theme and day/night timer, a new theme seemed like the cleanest way to add support for keeping the app's theme in-sync with the system.
Most of the magic is handled by values-night/theme.xml, but the comments action had a few things I needed to handle in onStart.  I haven't done Android development before, but this seemed like the right way to go about it.
Feel free to integrate (or not) this pull request as you see fit.  I won't be offended either way.

Add "Material (auto)" theme that follows the system dark/light mode.

---

app/src/main/java/com/simon/harmonichackernews/utils/ThemeUtils.java

Because `ComposeActivity` was the only place calling `ThemeUtils.setupTheme` with `specialFlags=false`, its status bar was not updated in light theme. Now it is always updated to match theme color
Before:
After:

Set correct status bar color when writing comments

---

app/src/main/java/com/simon/harmonichackernews/AboutActivity.java
app/src/main/java/com/simon/harmonichackernews/CommentsActivity.java
app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/CommentsRecyclerViewAdapter.java
app/src/main/java/com/simon/harmonichackernews/MainActivity.java
app/src/main/java/com/simon/harmonichackernews/SettingsActivity.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/StoryRecyclerViewAdapter.java
app/src/main/java/com/simon/harmonichackernews/SubmissionsActivity.java
app/src/main/java/com/simon/harmonichackernews/WelcomeActivity.java
app/src/main/java/com/simon/harmonichackernews/utils/Utils.java
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/activity_submissions.xml
app/src/main/res/layout/activity_welcome.xml
app/src/main/res/layout/fragment_stories.xml

This pr refactors part of padding selection logic to improve consistency with the original design of the app, fix bugs, and remove hacky parts. I've added short explanations of the changes to the commits but all you really need to know is in this link: [Why would I want to fitsSystemWindows](https://medium.com/androiddevelopers/why-would-i-want-to-fitssystemwindows-4e26d9ce1eec)
This fixes #34 and a couple other visual bugs. However, I'm publishing it as a draft because I have some questions and I tested only some combinations of settings. I am considering adding automated screenshots (e.g. using fastlane) to simplify testing all the combinations. Also I've mostly skipped comments screen because it is the most complicated one and it's not obvious if it can be simplified.

Refactor part of padding logic

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java

Android 13 introduced its own UI for copying, so this toast is unnecessary
https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#duplicate-notifications

Don't show copy toast on Android 13+

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java

The result of these inflations is not used and actual layout inflation
is performed by parent class, so they can be safely removed.
NB: I didn't bother to benchmark if there is any startup speed
difference, but it should be ever so slightly faster.

Remove unnecessary layout inflations

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/StoryRecyclerViewAdapter.java

The search text previously disappeared once the result loaded which was quite frustrating when you wanted to adjust the query.
Now the UI keeps the showing the search text even after the results are loaded.

Keep search text in UI

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java

The webview threw an exception when it was destroyed. This exception was thrown because before destroying it was instructed to load about:blank which happened asynchronously in the background. Sometimes before it finished loading it we would first call `destroy` and when the loading was finished it wanted to modify the webview. However after calling `destroy` it is not allowed to call anything on the webview and the exception was raised.
This didn't always happen and some sites were more prone to it which I assume is because they took longer to unload before about:blank could be loaded.
Loading about:blank before permanently destroying the webview isn't that useful and anyway and the stackoverflow post that introduced that pattern doesn't explain it so I guess it should be save to remove.

Fix webview exception

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/StoryRecyclerViewAdapter.java

There is no logical reason to refresh while you are typing. However, the refresh would have revealed an invalid cache and would start loading the results from the previous search.
You could reproduce this with:
1. Search something
2. Go to the main screen
3. Go to the search
4. Refresh by pulling from the top
Now the refresh gesture is disabled while you are in the search and no results have been loaded.

Disable refresh while typing the search query

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/SubmissionsActivity.java
app/src/main/java/com/simon/harmonichackernews/UserDialogFragment.java
app/src/main/java/com/simon/harmonichackernews/network/NetworkComponent.java
app/src/main/java/com/simon/harmonichackernews/network/UserActions.java
app/src/main/java/com/simon/harmonichackernews/network/VolleyOkHttp3StackInterceptors.java
app/src/main/java/com/simon/harmonichackernews/utils/ArchiveOrgUrlGetter.java
app/src/main/java/com/simon/harmonichackernews/utils/FileDownloader.java

Using singletons as recommended by [OkHttp](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#okhttpclients-should-be-shared) and [Volley](https://google.github.io/volley/requestqueue.html#use-a-singleton-pattern).
Also cleaned up most of the warnings in `VolleyOkHttp3StackInterceptors`.

Use singletons for OkHttp and Volley classes

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java

This addresses two problems.
The first one is a rare crash in CommentsFragment that can happen if
fragment gets destroyed after executing onCreate but before
onViewCreated. In this case webView is null which causes
NullPointerException.
The second one is a memory leak that can happen if fragment's view is
destroyed, but fragment itself is not. In this case requests will still
hold references to the layout in their listeners but the layout is
supposed to be free for garbage collection at this point. Note that
technically this doesn't change anything because the fragment itself
still holds references to the views. Still, this code is less wrong
than the old version.

Use onDestroyView fragment methods for cleanup

---

app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java
app/src/main/java/com/simon/harmonichackernews/CommentsRecyclerViewAdapter.java
app/src/main/res/layout/comments_header.xml

For some reason selecting text triggered insets listener which called
notifyItemChanged on the header causing the header ViewHolder to bind
again and drop the selection.

Make text post text selectable

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/simon/harmonichackernews/CommentsActivity.java
app/src/main/java/com/simon/harmonichackernews/MainActivity.java
app/src/main/java/com/simon/harmonichackernews/utils/ThemeUtils.java
app/src/main/res/anim/hold.xml
app/src/main/res/values-v30/styles.xml
app/src/main/res/values/themes.xml

Quite a lot of logic here. The idea is to use the default activity transition when starting the comments screen. Previously, we could not do this because the CommentsActivity had a bunch of weird styling (due to SwipeBack). When SwipeBack is active, nothing is changed this way.
First of all, the default theme for CommentsActivity is now AppTheme as this is seemingly required to get the animation to play. Then ThemeUtils may change the theme. For API < 30, we keep SwipeBack as the default theme and don't true to change anything.
For API >= 30, we need to set translucency of the activity to true to enable SwipeBack peeking so this is done. We only do this is SwipeBack is active though because this messes up the animation otherwise. Somewhat surprisingly, on API >= 34, translucency to true …

New comment transition

---

app/src/main/java/com/simon/harmonichackernews/network/JSONParser.java

I noticed this while poking around the different layouts, but this page doesn't seem to work. Perhaps Algolia's schema has changed, but `.hits[].title` isn't guranteed to exist anymore -- it seems that comment hits now return `story_title` instead. 
While testing, I also noticed that `story_url` doesn't always exist, even if the hit is a comment. For instance:
```bash
curl https://hn.algolia.com/api/v1/search_by_date?tags=author_pg&hitsPerPage=999 | jq '.hits[] | select(._tags[0] == "comment") | has("story_url")'
```
Doesn't always return true 😞 
This PR basically fixes the two issues above. I also considered wrapping this loop in a try-catch block, but wasn't sure if you'd prefer to fail closed on any parsing issues (perhaps no results is better than partial but missing results?). I'm …

Fix user submissions failing to load.

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java

Per the tin.
It looks like the regression was introduced in https://github.com/SimonHalvdansson/Harmonic-HN/commit/67837bb50f04cf20f12548b73478169ee9fa3609, which modified the search API endpoint here:
https://github.com/SimonHalvdansson/Harmonic-HN/blob/259a36f11474687145f2a984c9b0d82087fcc9ee/app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java#L653-L660
`relevance` was always false, so the API endpoint always resolved to `/api/v1/search_by_date/...`.
Closes https://github.com/SimonHalvdansson/Harmonic-HN/issues/115

Revert search sorting behaviour.

---

app/src/main/java/com/simon/harmonichackernews/SettingsActivity.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/SubmissionsActivity.java
app/src/main/java/com/simon/harmonichackernews/adapters/StoryRecyclerViewAdapter.java
app/src/main/java/com/simon/harmonichackernews/utils/SettingsUtils.java
app/src/main/res/xml/root_preferences.xml

This comment adds a feature to hide the number of comments of a story in the list view. It replaces the number of comments with a dot if there is any, or nothing if there is no comment.
Option is disabled by default (comments count is displayed), and does not show-up during initial setup.
This allows a more zen approach to browsing for interesting stories. This toggle+hide story points prevents appeal to popularity while selecting a story to read.  
* Tested loading the app without any setting change
* Tested changing setting, going back to list view, restarting app
* Checked: setting unset, story with no comments, stories with >0 comments
* Loaded Hot Stories page and New Stories page
| Hot Stories | New Stories | Setting page |
| ----------- | ------------ | ------|
| …

Feat: Add option to hide comments count in list view

---

app/src/main/java/com/simon/harmonichackernews/adapters/StoryRecyclerViewAdapter.java
app/src/main/java/org/sufficientlysecure/htmltextview/HtmlFormatter.java

`Html.fromHtml()` formats code blocks by inserting non-breaking spaces, `\u00A0`. This made words break unexpectedly since the entire line is considered a single word. 
The old behavior was to fit as much as possible on one line, then jump to the next, disregarding word boundaries, which is much harder to read.
This reverts non-breaking spaces to regular spaces.

Issue rendering code blocks where words would break unexpetedly

---

app/src/main/java/com/simon/harmonichackernews/network/UserActions.java

As jonas-w mentioned in #161 the voting direction (upvote, downvote or vote removing) isn't mentioned in the toast. To give better feedback of the action taken this commit now includes them. Since the information was already available in the method it was quite straight forward to implement it.
**Screenshot**:

Add the direction of the vote to the toast

---

app/src/main/java/com/simon/harmonichackernews/AboutActivity.java
app/src/main/java/com/simon/harmonichackernews/MainActivity.java
app/src/main/java/com/simon/harmonichackernews/utils/Changelog.java
app/src/main/res/layout/activity_about.xml

Previously the changelog was only displayed after and update, however it is sometimes quite handy to view the changelog to see what changed in the recent versions. Moreover I sometimes don't have the time to check the changelog when the update is released but want to read it a little bit later.
**About the implementation**
The text of the changelog is moved into it's own file, however the code for the popup itself is not shared. Reason for this is that the update dialog links to GitHub but such a button doesn't make sense here as the about page already has a link to GitHub.
**Screen Capture:**
https://github.com/SimonHalvdansson/Harmonic-HN/assets/21206831/2d571a43-43b1-4738-93af-ad29fc37973b

Add a changelog button to the about page

---

app/src/main/java/com/simon/harmonichackernews/AboutActivity.java
app/src/main/res/layout/activity_about.xml

While deploying a custom version of the app to my phone I wanted to be sure that the deployed app really is the release version.
Therefore I added this warning in the about section if the app is not a release version. On release build nothing changed. While most users hopefully should never see this, it should make it easier for devs to troubleshoot problems.
The commit also adds padding to the last button on the about page so that it doesn't hug the bottom that much.
**Screenshot:**

Display the debug indicator on the about page

---

.github/workflows/push.yml
app/build.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

This PR updates gradle and the build actions, fixes some deprecation warnings and improves CI speed from around 12min down to 3min. Of course the first commit with the new CI won't be any faster as there won't be a cache but future build should benefit from the cache.
Most of the speedup comes from a better/more agressive cache strategy.

Modernize Build

---

app/src/main/java/com/simon/harmonichackernews/ComposeActivity.java

Before this commit, clicking on a link in the comment you are replying to wouldn't have any effect.
Now it opens the link as expected and and still preserves the comment you have written so far.
This isn't quite what #167 described but I discovered this bug by trying to recreate his problem which sometimes caused app crashes which I could recreate on older commits but no longer seems to exist on `main`.

Fix link opening from reply

---

app/src/main/res/xml/main_split_config.xml

This PR makes the "foldable mode" work with the Galaxy Z fold 6. When unfolded, the Z Fold 6 seems to be 707dp in width (portrait mode), which was less than the 840 configured in `main_split_config.xml`.

Enable foldable support for Z Fold 6

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java

The search results always seemed really irrelevant compared to searching directly on https://hn.algolia.com
I dug a bit, and found out that the typoTolerance is set to true per default, which yields often times very irrelevant results, for example the results for 'ETF':
```
~ curl 'https://hn.algolia.com/api/v1/search_by_date?query=ETF&tags=story' 2>/dev/null | jq '.hits[].title'
"The false reason of the cost of AI in the world run of cost reduction"
"Intel P Core vs. E Core actual advantage?"
"Who is NOT moving from C/C++ to Rust?"
"Why Chiefs of Staff Need an Effective Framework"
"Show HN: Ell – A command-line interface for LLMs written in Bash"
"LazyLLM: Dynamic Token Pruning for Efficient Long Context LLM Inference"
"Show HN: AI Daily Planner"
"Show HN: Test Pilot Hub – A Platform to …
```

Set search typo tolerance to min

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/utils/Changelog.java
app/src/main/java/com/simon/harmonichackernews/utils/SettingsUtils.java
app/src/main/res/values/strings.xml

This commit introduces a new view for displaying the user's browsing history.
The `attemptRefresh()` method now handles loading and displaying stories from the user's history when the `adapter.type` is set to the history index.
This feature enhances the user experience by providing a convenient way to access previously viewed stories.

Add history view

---

.gitignore
app/build.gradle
app/src/main/java/com/simon/harmonichackernews/SettingsActivity.java
app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java
app/src/main/java/com/simon/harmonichackernews/data/History.kt
app/src/main/java/com/simon/harmonichackernews/data/Story.java
app/src/main/java/com/simon/harmonichackernews/network/JSONParser.java
app/src/main/java/com/simon/harmonichackernews/utils/HistoriesUtils.kt
app/src/main/java/com/simon/harmonichackernews/utils/Utils.java
app/src/main/java/com/simon/harmonichackernews/utils/UtilsKt.kt
build.gradle

My [previous implementation](https://github.com/SimonHalvdansson/Harmonic-HN/commit/167851f3598ecdc48d53b8880ea8e1f238a88554) of history doesn't have any sort mechanism. I think it's better to sort the history by clicked time. So the last clicked item is on top.
Hence, it required saving the time when the story is clicked by user.
Also the time shown on `meta_view` is not time from api response but using the time when the story is clicked.
The way history is saved to sharePrefs is similar to Bookmark.
```xml
<string name="com.simon.harmonichackernews.KEY_SHARED_PREFERENCES_HISTORIES">
44023680q1747630184892-44025484q1747630183027-44024759q1747630177525-44020591q1747630175592
</string>
```

Rework history

---

app/src/main/java/com/simon/harmonichackernews/StoriesFragment.java

Sometimes you forget to upvote a story before leaving it, this PR adds a menu item for doing so on the stories page.

add upvote item to story popup menu

---

app/src/main/java/com/simon/harmonichackernews/utils/ThemeUtils.java
app/src/main/res/values-night/themes.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/themes.xml

I added two more automatic themes for dark/light and black/light, which should address issue #118.
While this works as expected I have a couple of questions about some code pieces I stumbled upon.
In `ThemeUtil.java` there is the following api level check just for the material theme:
```Java
switch (theme) {
case "material_daynight":
//below 30, default on comments is swipeBack so if we don't use it we need to change to a normal theme
if (Build.VERSION.SDK_INT < 30) {
if (!swipeBack) {
activity.setTheme(R.style.AppThemeMaterialDayNight);
}
} else {
//at and above 30, the default is AppTheme so if we use swipeBack we need to change
if (swipeBack) {
activity.setTheme(R.style.ThemeSwipeBackNoActionBarMaterialDayNight);
}
}
break;
```
I don't quite get why that logic would only be necessary …

Add more auto themes
